import { semanticDigest } from '../canonical-json.js';
import type { PythonEnvironmentPlan, PythonPlatformPlan } from './environment-plan.js';

export interface PythonConsumerLock {
  content: string;
  digest: string;
  path: string;
  platformFamilyId: string;
  pythonMinor: string;
}

export interface PythonConsumerPlatformContract {
  healthChecks: {
    args: string[];
    command: string;
  }[];
  install: {
    pip: string[];
    uv: string[];
  };
  lockPath: string;
  platformFamilyId: string;
  pythonMinor: string;
  requiresPython: string;
  verify: string[][];
}

export interface PythonConsumerContract {
  application: PythonEnvironmentPlan['application'];
  configuration: {
    environmentTemplatePath: string;
    indexUrl: string;
    pipConfigTemplatePath: string;
  };
  generatedFromPlanId: string;
  installationOwner: 'consumer-infrastructure';
  platforms: PythonConsumerPlatformContract[];
  publication?: {
    owner: string;
    package: string;
    version: string;
  };
  schemaVersion: 1;
}

export interface PythonConsumerBundleDocuments {
  contract: PythonConsumerContract;
  documents: {
    content: string;
    path: string;
  }[];
  locks: PythonConsumerLock[];
}

export interface CreatePythonConsumerBundleDocumentsOptions {
  genericOwner: string;
  giteaBaseUrl: string;
  publicationId: string;
  pypiOwner: string;
}

function closedIndexUrl(giteaBaseUrl: string, owner: string): string {
  const base = giteaBaseUrl.replace(/\/+$/u, '');
  return `${base}/api/packages/${encodeURIComponent(owner)}/pypi/simple`;
}

function hashesForPackage(
  plan: PythonEnvironmentPlan,
  platform: PythonPlatformPlan,
  name: string,
  version: string
): string[] {
  return [
    ...new Set(
      plan.wheels
        .filter(
          (wheel) =>
            wheel.package === name &&
            wheel.version === version &&
            wheel.platforms.includes(platform.platformFamilyId)
        )
        .map((wheel) => wheel.sha256)
    ),
  ].sort();
}

export function createPythonRequirementsLock(
  plan: PythonEnvironmentPlan,
  platform: PythonPlatformPlan
): string {
  const lines = [
    '# Generated by airgap-sync. Install with --no-deps --require-hashes --only-binary=:all:.',
  ];
  for (const pkg of [...platform.packages].sort((left, right) =>
    left.name.localeCompare(right.name)
  )) {
    const hashes = hashesForPackage(plan, platform, pkg.name, pkg.version);
    if (hashes.length === 0) {
      throw new Error(
        `${pkg.name}==${pkg.version} has no collected wheel hash for ${platform.platformFamilyId}`
      );
    }
    lines.push(
      `${pkg.name}==${pkg.version} \\`,
      ...hashes.map(
        (hash, index) => `    --hash=sha256:${hash}${index === hashes.length - 1 ? '' : ' \\'}`
      )
    );
  }
  return `${lines.join('\n')}\n`;
}

function genericPublication(
  plan: PythonEnvironmentPlan,
  options: CreatePythonConsumerBundleDocumentsOptions
): NonNullable<PythonConsumerContract['publication']> {
  return {
    owner: options.genericOwner,
    package: `${plan.application.name}-${plan.coverage.policy.id}`,
    version: `${plan.application.version}+plan.${plan.planId.slice(0, 12)}.pub.${options.publicationId.slice(0, 12)}`,
  };
}

export function createPythonConsumerLocks(plan: PythonEnvironmentPlan): PythonConsumerLock[] {
  return plan.platforms.map<PythonConsumerLock>((platform) => {
    if (!platform.requirementsLockPath) {
      throw new Error(`Python platform ${platform.platformFamilyId} has no requirements lock path`);
    }
    const content = createPythonRequirementsLock(plan, platform);
    return {
      content,
      digest: semanticDigest(content),
      path: platform.requirementsLockPath,
      platformFamilyId: platform.platformFamilyId,
      pythonMinor: platform.pythonMinor,
    };
  });
}

export function createPythonConsumerBundleDocuments(
  plan: PythonEnvironmentPlan,
  options: CreatePythonConsumerBundleDocumentsOptions
): PythonConsumerBundleDocuments {
  const indexUrl = closedIndexUrl(options.giteaBaseUrl, options.pypiOwner);
  const locks = createPythonConsumerLocks(plan);
  const healthChecks = plan.verification?.healthChecks ?? [];
  const publication = genericPublication(plan, options);
  const contract: PythonConsumerContract = {
    application: plan.application,
    configuration: {
      environmentTemplatePath: 'consumer.env.template',
      indexUrl,
      pipConfigTemplatePath: 'pip.conf.template',
    },
    generatedFromPlanId: plan.planId,
    installationOwner: 'consumer-infrastructure',
    platforms: plan.platforms.map((platform) => {
      const lock = locks.find(
        (candidate) => candidate.platformFamilyId === platform.platformFamilyId
      )!;
      return {
        healthChecks,
        install: {
          pip: [
            `python${platform.pythonMinor}`,
            '-m',
            'pip',
            'install',
            '--index-url',
            indexUrl,
            '--only-binary=:all:',
            '--no-deps',
            '--require-hashes',
            '-r',
            lock.path,
          ],
          uv: [
            'uv',
            'pip',
            'sync',
            '--default-index',
            indexUrl,
            '--only-binary=:all:',
            '--require-hashes',
            lock.path,
          ],
        },
        lockPath: lock.path,
        platformFamilyId: platform.platformFamilyId,
        pythonMinor: platform.pythonMinor,
        requiresPython: platform.requiresPython,
        verify: [
          [`python${platform.pythonMinor}`, '-m', 'pip', 'check'],
          ...healthChecks.map((check) => [check.command, ...check.args]),
        ],
      };
    }),
    publication,
    schemaVersion: 1,
  };
  return {
    contract,
    documents: [
      {
        content: [
          '[global]',
          `index-url = ${indexUrl}`,
          'disable-pip-version-check = true',
          '',
        ].join('\n'),
        path: 'pip.conf.template',
      },
      {
        content: [
          `PIP_INDEX_URL=${indexUrl}`,
          `UV_DEFAULT_INDEX=${indexUrl}`,
          'PIP_ONLY_BINARY=:all:',
          '',
        ].join('\n'),
        path: 'consumer.env.template',
      },
      {
        content: `${JSON.stringify(contract, null, 2)}\n`,
        path: 'consumer-contract.json',
      },
    ],
    locks,
  };
}
